### ISSUE TITLE
Please release lib version

### ISSUE THREAD

**Issue by ItaloCobains** [encode/broadcaster#103]
I need the functionality of a feature that sends the redis url password to asyncio_redis version 0.2.0, but I cloned your repository and saw that it is already available. I have an app in production that really needs this. I'll end up having to open a fork of your app or use another lib if that doesn't work.

0.2.0:
```py
    async def connect(self) -> None:
        self._pub_conn = await asyncio_redis.Connection.create(self._host, self._port)
        self._sub_conn = await asyncio_redis.Connection.create(self._host, self._port)
        self._subscriber = await self._sub_conn.start_subscribe()
```

current version repo:
```py
    async def connect(self) -> None:
        kwargs = {"host": self._host, "port": self._port, "password": self._password}
        self._pub_conn = await asyncio_redis.Connection.create(**kwargs)
        self._sub_conn = await asyncio_redis.Connection.create(**kwargs)
        self._subscriber = await self._sub_conn.start_subscribe()

```

**Comment by Mark90** [comment]
In case anyone read my previous comment and got their hopes up, using `rediss://` actually gives problems in the `asyncio_redis` library that broadcaster depends on. So I was wrong in saying that master branch works fine (for this particular usecase anyway)

**Comment by alex-oleshkevich** [comment]
@Kludex let's merge #110 and #111 and publish a new version?

**Comment by alex-oleshkevich** [comment]
Tracked in https://github.com/encode/broadcaster/issues/113
