### ISSUE TITLE
Asyncio_redis -  "Maintainers needed!" - Update asyncio_redis library to redis-py and add SSL connection support

### ISSUE THREAD

**Issue by caiquilipe** [encode/broadcaster#107]
Currently, the asyncio_redis library is not receiving regular maintenance. This library is essential for handling asynchronous operations related to Redis. However, its lack of maintenance may lead to security issues and delays in resolving bugs and incompatibilities.

Additionally, the library does not natively support SSL connections, which is crucial for environments where security is a priority.

I suggest considering migrating the asyncio_redis library to redis-py, which is well-maintained and widely used by the community. Furthermore, adding support for SSL connections would be highly beneficial to increase the security and compatibility of the library with various environments.

**Comment by alex-oleshkevich** [comment]
Resolved in #111
