### ISSUE TITLE
Unsubscribing issue in Broadcast class

### ISSUE THREAD

**Issue by mdi80** [encode/broadcaster#108]
Hi,

I was working with your `Broadcast` class and noticed a bug related to websocket disconnection. In the `subscribe` method of the `Broadcast` class, when a user disconnects from the websocket, the code after `yield Subscriber(queue)` will never execute. This could potentially lead to increased memory usage if items are never removed from the `_subscribers` dictionary.

Thank you for your great code!

**Comment by alex-oleshkevich** [comment]
Fixed in #112
