### ISSUE TITLE
Version 0.3

### ISSUE THREAD

**Issue by alex-oleshkevich** [encode/broadcaster#113]
PRs
- [x] https://github.com/encode/broadcaster/pull/110
- [x] https://github.com/encode/broadcaster/pull/112
- [x] https://github.com/encode/broadcaster/pull/111
- [x] https://github.com/encode/broadcaster/pull/114
- [x] https://github.com/encode/broadcaster/pull/117
- [x] https://github.com/encode/broadcaster/pull/102
- [x] https://github.com/encode/broadcaster/pull/125
- [x] https://github.com/encode/broadcaster/pull/128

Fixes:
- [x] https://github.com/encode/broadcaster/issues/108
- [x] https://github.com/encode/broadcaster/issues/107
- [x] https://github.com/encode/broadcaster/pull/104 
- [x] https://github.com/encode/broadcaster/issues/90
- [x] https://github.com/encode/broadcaster/issues/103
- [x] https://github.com/encode/broadcaster/issues/55 ?
- [ ] https://github.com/encode/broadcaster/issues/65 ?
- [x] https://github.com/encode/broadcaster/issues/44 ?
- [x] https://github.com/encode/broadcaster/issues/42
- [x] https://github.com/encode/broadcaster/issues/51
- [x] https://github.com/encode/broadcaster/issues/5

**Comment by alex-oleshkevich** [comment]
Waiting for https://github.com/encode/broadcaster/pull/125
Cooling down 7d and then will release 0.3

**Comment by laxuscullen** [comment]
This release will go public even with #127 open?

**Comment by alex-oleshkevich** [comment]
Ok, I am rolling out 0.3.
