### ISSUE TITLE
Fix type hint on `Subscriber.__aiter__`

### ISSUE THREAD

**Issue by wookie184** [encode/broadcaster#136]
I've read the contributing guidelines and believe this is clear enough to open an issue directly. I might open a PR at some point but if someone else can get to it first please do!

Current type hint: https://github.com/encode/broadcaster/blob/23c9b40136231d0a78d1299588b62d7162067ff4/broadcaster/_base.py#L113
Incorrect complaint by pyright cause by this:
![image](https://github.com/user-attachments/assets/2f4f6bc9-4400-4ca1-b6dd-a91f853bbb96)

Correct type hint:
```python
async def __aiter__(self) -> AsyncGenerator[Event, None]: 
```
Or the also correct and a bit nicer (and consistent with `Broadcast.subscribe`):
```python
async def __aiter__(self) -> AsyncIterator[Event]:
```

**Comment by alex-oleshkevich** [comment]
It is a generator because it `yield`'s.

**Comment by wookie184** [comment]
`collections.abc.AsyncGenerator` inherits from `collections.abc.AsyncIterator`, so you can use the more generic `AsyncIterator` if you aren't using any generator-specific functionality (like sending values to the generator). This is mentioned in the typing docs [here](https://docs.python.org/3/library/typing.html#typing.AsyncGenerator).

I mentioned it because it's already used for the async generator a few lines above. Either option is fine though:
https://github.com/encode/broadcaster/blob/23c9b40136231d0a78d1299588b62d7162067ff4/broadcaster/_base.py#L90

**Comment by alex-oleshkevich** [comment]
Merged.
