### ISSUE TITLE
Backend clients additional keyword arguments

### ISSUE THREAD

**Issue by JoseKilo** [encode/broadcaster#143]
I've found myself wanting to add a `retry` parameter to the Redis client used by the `RedisBackend`.

Documentation:
https://redis-py-uglide.readthedocs.io/en/latest/connections.html
https://redis-py-uglide.readthedocs.io/en/latest/retry.html

At the moment the client gets initialized by the backend without support for additional parameters.
The only way to affect the Redis client is by the connection url, which in fact can be used to configure some settings, like:
`redis://:@localhost:6380?retry_on_timeout=yes&socket_timeout=5&socket_connect_timeout=5`

However the `retry` parameter expects an object, so it can't be modified by the url.

Another alternative would be writing a custom backend, but that would imply copying code from the existing backend and keeping it in sync, which I'd prefer to avoid.

Would you consider a PR to forward any additional parameters from the `Broadcast` object to the backends and to the underlying clients ? Something that could be used like this:

```python
retry = redis.retry.Retry(
    backoff=redis.backoff.ExponentialBackoff(),
    retries=10,
)
async with Broadcast("redis://localhost:6379", retry=retry) as broadcast:
    ...
```

I'm mostly interested in the Redis backend myself, but I think Postgres and Kafka could benefit from the same feature.

**Comment by alex-oleshkevich** [comment]
We provide custom backend support for this purpose.

**Comment by alex-oleshkevich** [comment]
If you still want to contribute, you can make a PR to add the retry feature to the RedisBackend.

**Comment by JoseKilo** [comment]
I don't disagree, my only concern is having to either:
- import / access a private member from the library in order to extend it (`broadcaster._backends` is private)
- or copy the whole `RedisBackend` class (~50 lines)

And having to keep an eye on any changes made upstream to keep my custom backend updated.

For example, this would work in my case, but I expect compatibility issues in the future.

```python
class CustomBroadcastBackend(broadcaster._backends.redis.RedisBackend):  # noqa: SLF001
    def __init__(self, url: str) -> None:
        retry = redis.retry.Retry(
            backoff=redis.backoff.ExponentialBackoff(),
            retries=10,
        )
        self._conn = redis.asyncio.Redis.from_url(url, retry=retry)
        self._pubsub = self._conn.pubsub()
        self._ready = asyncio.Event()
        self._queue: asyncio.Queue[Event] = asyncio.Queue()
        self._listener: asyncio.Task[None] | None = None
```

**Comment by JoseKilo** [comment]
Another option would be accepting any keyword arguments `**kwargs: Any` and assume that they're additional arguments for the internal client:

```patch
 class Broadcast:
-    def __init__(self, url: str | None = None, *, backend: BroadcastBackend | None = None) -> None:
+    def __init__(self, url: str | None = None, *, backend: BroadcastBackend | None = None, **kwargs: Any) -> None:
         assert url or backend, "Either `url` or `backend` must be provided."
-        self._backend = backend or self._create_backend(cast(str, url))
+        self._backend = backend or self._create_backend(cast(str, url), **kwargs)
         self._subscribers: dict[str, set[asyncio.Queue[Event | None]]] = {}

-    def _create_backend(self, url: str) -> BroadcastBackend:
+    def _create_backend(self, url: str, **kwargs: Any) -> BroadcastBackend:
         parsed_url = urlparse(url)
         if parsed_url.scheme in ("redis", "rediss"):
             from broadcaster._backends.redis import RedisBackend

-            return RedisBackend(url)
+            return RedisBackend(url, **kwargs)
```

```patch
 class RedisBackend(BroadcastBackend):
-    def __init__(self, url: str):
-        self._conn = redis.Redis.from_url(url)
+    def __init__(self, url: str, **kwargs: typing.Any):
+        self._conn = redis.Redis.from_url(url, **kwargs)
```

But obviously static type analysis wouldn't work on any extra params.

And it would mean that you can pass different params depending on the chosen backend, which maybe is against the design principles of the library: should the interface stay the same regardless of which backend you're using? even for advanced low-level settings?

Your options 3 + 2 sound good to me too, but as you said, they requires more changes.

The only problem with option 1 is that it could solve this particular problem, but other users may need to customize other internal client settings.
