### ISSUE TITLE
What is the License for this project?

### ISSUE THREAD

**Issue by MarcDufresne** [encode/broadcaster#29]
I am compiling a report on 3rd party library usage at my company and noticed that broadcaster doesn't have a LICENSE file.

**Comment by AntonOfTheWoods** [comment]
@MarcDufresne , [looks like it's BSD](https://github.com/encode/broadcaster/blob/master/setup.py#L58), though it is not particularly well advertised.

**Comment by rafalp** [comment]
I'll mark this as documentation from lack of better labels. We'll have to double check and add LICENSE file to the repo.
