### ISSUE TITLE
Add GitHub action to run tests

### ISSUE THREAD

**Issue by rafalp** [encode/broadcaster#39]

**Comment by tomchristie** [comment]
For reference... https://github.com/encode/httpx/blob/master/.github/workflows/test-suite.yml

**Comment by rafalp** [comment]
@hramezani I've merged your PR but test cases aren't good - they hang causing tests suite to timeout.

**Comment by rafalp** [comment]
I've given this some attention and found that Kafka backend is hanging withing `next_published`, with `await self._consumer.getone()` never returning.

**Comment by Kludex** [comment]
I've skipped Kafka for now. I'm cleaning this project. I'll update the test before I finish the cleanup.

Pipeline is already green with 88% coverage, and Kafka test skipped.
