### ISSUE TITLE
Add GitHub action for publishing

### ISSUE THREAD

**Issue by rafalp** [encode/broadcaster#40]

**Comment by hramezani** [comment]
This [PR](https://github.com/encode/broadcaster/pull/11) might be related.

**Comment by rafalp** [comment]
@tomchristie could you please help with this?

**Comment by tomchristie** [comment]
Okay, so I'd suggest we get [the test suite actions setup first](https://github.com/encode/broadcaster/issues/39). If you need any help with that then let me know. Once those are rolling and confirmed, then I'd suggest next opening a PR to [add a publish action](https://github.com/encode/httpx/blob/master/.github/workflows/publish.yml) once the PR is open, I can setup the required PyPI token that we'll need for it.

Does that approach all make sense?

**Comment by rafalp** [comment]
@tomchristie it does, thanks! 👍

I'll reach back to you about the token when CI is setup!

**Comment by Kludex** [comment]
- Closed by #80

I need the PyPI token.
