### ISSUE TITLE
Kafka test hangs on "await subscriber.get()"

### ISSUE THREAD

**Issue by rafalp** [encode/broadcaster#42]
We now have tests suite courtesy of #11, but test for Kafka backend hands indefinitely on `await subscriber.get()`, causing tests suite to timeout:

https://github.com/encode/broadcaster/blob/435c35eefcf54192331a44881caf626a5993b2f0/tests/test_broadcast.py#L43

Sadly, I'm out of my depth here, and I'm unable to diagnose if this is problem with Kafka backend or test setup.

Help is welcome.

**Comment by florimondmanca** [comment]
Maybe unrelated, but there's something strange about the subscribe/unsubscribe implementations in the Kafka backend:


https://github.com/encode/broadcaster/blob/master/broadcaster/_backends/kafka.py

Essentially when we subscribe to a new channel, we add it to a set of channels, then get the Kafka consumer to subscribe to all those channels (topics). And when we unsubscribe from a specific channel, we unsubscribe, period. I wonder if this can cause issues when subscribing from two or more channels independently. Dunno if that's related to the test though.

**Comment by justinepdevasia** [comment]
Some experimentation result mentioned in https://github.com/encode/broadcaster/issues/44#issuecomment-956094210
