### ISSUE TITLE
Test hangs with Redis backend in Starlette/FastAPI

### ISSUE THREAD

**Issue by Buuntu** [encode/broadcaster#44]
Using the testing example from the [Starlette docs](https://www.starlette.io/testclient/#testing-websocket-sessions) with a route that uses a Redis websocket just hangs indefinitely:

```python
def test_websocket(client):
        with client.websocket_connect("/ws") as websocket:
            websocket.send_text("Hello WebSocket")
            data = websocket.receive_text()
            assert data == "Hello WebSocket"
```

this however, works fine:
```python
def test_websocket(client):
        with client.websocket_connect("/ws") as websocket:
            assert True
```

maybe it's related to this https://github.com/encode/broadcaster/pull/2#issuecomment-591407905 and https://github.com/encode/broadcaster/issues/42?

I think it's the same with a memory backend.  Has anyone successfully tested a Starlette websocket route?

UPDATE: I tried running `./scripts/test` locally from the broadcaster directory and it actually hangs for me on the redis test.  Anyone else getting that?

**Comment by justinepdevasia** [comment]
@Buuntu I too have got the same issue on testing `./scripts/test` for redis. on examining with `redis-cli monitor` command inside redis, it is seen that publishing to the channel happens before subscribe and it is waiting forever to get published data.The test examined is    
```python3
@pytest.mark.asyncio
async def test_redis():
    async with Broadcast("redis://localhost:6379") as broadcast:
        async with broadcast.subscribe("chatroom") as subscriber:
            await broadcast.publish("chatroom", "hello")
            event = await subscriber.get()
            assert event.channel == "chatroom"
            assert event.message == "hello"

 ```
Redis cli output   

<img width="495" alt="Screenshot 2021-11-01 at 3 23 28 PM" src="https://user-images.githubusercontent.com/40311683/139654029-3b9c3cd0-ad25-4955-a35d-b47038b72baf.png">

But it was working after adding a minimal delay before publish

```python3
import asyncio

@pytest.mark.asyncio
async def test_redis():
    async with Broadcast("redis://localhost:6379") as broadcast:
        async with broadcast.subscribe("chatroom") as subscriber:
            await asyncio.sleep(0.01)
            await broadcast.publish("chatroom", "hello")
            event = await subscriber.get()
            assert event.channel == "chatroom"
            assert event.message == "hello"
```
Redis cli output  

<img width="529" alt="Screenshot 2021-11-01 at 3 28 28 PM" src="https://user-images.githubusercontent.com/40311683/139654587-eb829c4c-96d2-42c9-be23-f44b88640e87.png">

In this case subscribe occur before publish and the test got passed.

**Comment by alex-oleshkevich** [comment]
We changed the underlying Redis library to redis-py. Can you please re-test if the issue is still there?

**Comment by alex-oleshkevich** [comment]
It does not hang either in tests nor in the example. I think this issue is fixed. 
Feel free to reopen.

**Comment by alex-oleshkevich** [comment]
Closing it as stalled. Feel free to reopen.
