### ISSUE TITLE
Uvicorn doesn't respond if redis wasn't started

### ISSUE THREAD

**Issue by nazareka** [encode/broadcaster#47]
I forgot to start redis, and i started fastapi with broadcaster, and uvicorn just didn't respond, i couldn't shutdown uvicorn, and didn't get any error
![image](https://user-images.githubusercontent.com/60483996/116824061-70205080-ab88-11eb-89d9-293dc3754550.png)

**Comment by Kludex** [comment]
This is not a `broadcaster` issue. 👀
