### ISSUE TITLE
Support for multiple servers

### ISSUE THREAD

**Issue by woile** [encode/broadcaster#5]
Kafka accept n + 1 servers to bootstrap initial cluster metadata.

https://aiokafka.readthedocs.io/en/stable/api.html#aiokafkaconsumer-class

**Comment by tomchristie** [comment]
First question would be what we want the `Broadcaster.__init__` interface to look like to support this.

Do we want to change it to `Broadcast(url: Union[str, List[str]])`, or something else?

We'd need to raise errors if the urls included mixed backend strings, or if multiple urls were used with a backend that only supports a single hostname for connections.
