### ISSUE TITLE
No notifications received with Postgres as backend

### ISSUE THREAD

**Issue by wkamer** [encode/broadcaster#53]
I'm trying to get broadcaster work with FastAPI and a PostgreSQL database with notifications enabled.

Here is the code I use

FastAPI (test_broadcaster.py)
```
from broadcaster import Broadcast

broadcast = Broadcast("postgres://<username>:<password>@localhost:5432/<database>")

async def broadcast_ws_receiver(websocket):
    async for message in websocket.iter_text():
        await broadcast.publish(channel="account", message=message)

async def broadcast_ws_sender(websocket):
    async with broadcast.subscribe(channel="account") as subscriber:
        async for event in subscriber:
            await websocket.send_text(event.message)
```
FastAPI (router.py)
```
from fastapi.routing import APIRouter
from fastapi.websockets import WebSocket
from fastapi.concurrency import run_until_first_complete

from test_broadcaster import broadcast_ws_sender, broadcast_ws_receiver

router = APIRouter()

@router.websocket("/broadcast")
async def broadcast_ws(websocket: WebSocket):
    await websocket.accept()
    
    await run_until_first_complete(
        (broadcast_ws_receiver, {"websocket": websocket}),
        (broadcast_ws_sender, {"websocket": websocket}),
    )
```
PostgreSQL (trigger name) # on the table account
account

PostgreSQL (trigger_function)
```
BEGIN
  PERFORM pg_notify(
    'account',
    json_build_object(
      'operation', TG_OP,
      'record', row_to_json(NEW)
    )::text
  );

  RETURN NEW;
END;
```
When making the websocket connection connection and update the table to trigger a notification, nothing happends. Also not when using
```
NOTIFY account, 'hello world';
```
When changing to Redis it is working flawless, from Redis to websocket and websocket to Redis.

Is this a bug? Or I'm missing something in the code?

**Comment by wkamer** [comment]
Is this tools still under development?

**Comment by rafalp** [comment]
I'm using broadcaster with Redis backend and it works fine, but AFAIR that's only backend that does. Something is very wrong with our tests suite IMHO. It's supposed to test other backends like memory, Kafka and PostgreSQL and tests for those pass, but in real world suddenly they don't.

**Comment by alex-oleshkevich** [comment]
Closing as stale.
