### ISSUE TITLE
can't define redis database number

### ISSUE THREAD

**Issue by vessaldaneshvar** [encode/broadcaster#54]
I review source code of backends related to connect redis backend
I can't connect to specific db in redis and this ignore in codebase of parse URI definition

in broadcaster/_backends/redis.py initialize RedisBackend by port and host , in this section must be define database number

redis://HOST[:PORT][?**db**=DATABASE[&password=PASSWORD]]

**db** is missing on URI define

**Comment by Kludex** [comment]
If someone is seeing this, and there's interest on creating a PR, feel free to do so.

I'm closing it because it's stale, and it doesn't look like there's interest on it.
