### ISSUE TITLE
Django Channels Layer compatibility

### ISSUE THREAD

**Issue by Archmonger** [encode/broadcaster#82]
[Django Channels Layers](https://channels.readthedocs.io/en/stable/topics/channel_layers.html) perform a similar task to broadcaster, but currently only works with `redis`.

Would be a nice addition if there was a built-in wrapper around broadcaster to be used as a drop-in replacement. Perhaps the dotted path would look something like `broadcaster.django.KafkaChannelLayer`?

This is definitely a task for > 1.0.0 release.

**Comment by alex-oleshkevich** [comment]
Closing as stale.

**Comment by Archmonger** [comment]
I believe the feature request is still valid. There still aren't any third-party channel layers for Django at the moment.
Would you rather fully reject the request as not planned instead?

**Comment by alex-oleshkevich** [comment]
On my options this should be a third-party package that integrates broadcaster and django. Like channels-redis does.
